### ISSUE TITLE
questions used on x86

### ISSUE THREAD

**Issue by nblog** [0xnobody/vmpattack#5]
hello friend.
I want to ask if I want to improve it to x86, where should I start, and what information should I read?
hope to get some help.
sincere thanks.

**Comment by 0xnobody** [comment]
Hello,
I did some basic analysis on 32-bit VMProtect 3 targets. The structure and semantics seemed to be exactly the same, just using x86 registers and processor features instead of the x64 ones. I suspect you could rather easily modify the source to support these, as all the logic flow should be exactly the same.

**Comment by nblog** [comment]
that's great!
thank for your reply.  😄
